spells = 	{
			laser={"down", "down", "right"},
			laser2={"down", "down", "left"},
			superjump={"down", "down", "down", "up"},
			cubespawn={"up", "right", "down", "left"},
			teleport={"right", "right", "right", "up"},
			teleport2={"left", "left", "left", "up"},
			shockwave={"up", "up", "up", "down"},
			timefreeze={"left", "down", "up", "right", "right"},
			invisibility={"right", "right", "down", "down", "up"},
			ceilingwalk={"up", "down", "up", "down", "up", "down"},
			floorwalk={"down", "up", "down", "up", "down", "up"},
			leftwalk={"left", "right", "left", "right", "left", "right"},
			rightwalk={"right", "left", "right", "left", "right", "left"},
			gamewin={"down", "down", "down", "down", "up", "left", "right", "up"},
			ascend={"up", "up", "down", "down", "left", "right", "left", "right"},
			}
			
spellnames = {
			{name="shoot laser", id="laser"},
			{name=false, id="laser2"},
			{name="super jump", id="superjump"},
			{name="create cube", id="cubespawn"},
			{name="teleport", id="teleport"},
			{name=false, id="teleport2"},
			{name="shockwave", id="shockwave"},
			{name="freeze time", id="timefreeze"},
			{name="invisibility", id="invisibility"},
			{name="ceilingwalk", id="ceilingwalk"},
			{name="floorwalk", id="floorwalk"},
			{name="wallwalk l", id="leftwalk"},
			{name="wallwalk r", id="rightwalk"},
			{name="???", id="gamewin"},
			{name="ascend", id="ascend"},
			}